AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/bundle
  NewCops: enable
  TargetRubyVersion: '3.0.0'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

require: rubocop-rails
